In [1]:
def Question1():
    result=[]
    for x in range(2000,3200):
        if ((x%7==0) and (x%5!=0)):
             result.append(x)
    return result 
Question1()  


[2002,
 2009,
 2016,
 2023,
 2037,
 2044,
 2051,
 2058,
 2072,
 2079,
 2086,
 2093,
 2107,
 2114,
 2121,
 2128,
 2142,
 2149,
 2156,
 2163,
 2177,
 2184,
 2191,
 2198,
 2212,
 2219,
 2226,
 2233,
 2247,
 2254,
 2261,
 2268,
 2282,
 2289,
 2296,
 2303,
 2317,
 2324,
 2331,
 2338,
 2352,
 2359,
 2366,
 2373,
 2387,
 2394,
 2401,
 2408,
 2422,
 2429,
 2436,
 2443,
 2457,
 2464,
 2471,
 2478,
 2492,
 2499,
 2506,
 2513,
 2527,
 2534,
 2541,
 2548,
 2562,
 2569,
 2576,
 2583,
 2597,
 2604,
 2611,
 2618,
 2632,
 2639,
 2646,
 2653,
 2667,
 2674,
 2681,
 2688,
 2702,
 2709,
 2716,
 2723,
 2737,
 2744,
 2751,
 2758,
 2772,
 2779,
 2786,
 2793,
 2807,
 2814,
 2821,
 2828,
 2842,
 2849,
 2856,
 2863,
 2877,
 2884,
 2891,
 2898,
 2912,
 2919,
 2926,
 2933,
 2947,
 2954,
 2961,
 2968,
 2982,
 2989,
 2996,
 3003,
 3017,
 3024,
 3031,
 3038,
 3052,
 3059,
 3066,
 3073,
 3087,
 3094,
 3101,
 3108,
 3122,
 3129,
 3136,
 3143,
 3157,
 3164,
 3171,
 3178,
 3192,
 3199]

In [13]:
def Question2(n):
    if(n==0):
        print("factorial of 0 is 1")
    else:
        res=1
        while(n>=1):
            res=res*(n)
            n=n-1
        return res
n=int(input())
Question2(n)


 5


120

In [7]:
def Question3(n):
    i=1
    res={}
    while(i<=n):     
        res[i]=i*i
        i=i+1
    return res
n=int(input())
Question3(n)
        

 8


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [3]:
def Question4(char,i):
    res=""
    for x in range (0,len(char)):
        if(x!=(i-1)):      
            res=res+char[x]
    return res
i=int(input())
char=str(input())
Question4(char,i)


 2
 hosi


'hsi'

In [7]:
import numpy as np
def Question5(minV,maxV,minS,maxS):
    numpy=np.random.randint(minV,maxV,size=(minS,maxS))
    print("Original numpy Array:")
    print(numpy)
    print("My Final List:")
    print(numpy.tolist())
    
minV=int(input())
maxV=int(input())
minS=int(input())
maxS=int(input())
Question5(minV,maxV,minS,maxS)


 3
 9
 2
 4


Original numpy Array:
[[7 7 8 7]
 [5 4 3 5]]
My Final List:
[[7, 7, 8, 7], [5, 4, 3, 5]]


In [9]:
import numpy as np
np1 =np.array([0,1,2])
np2 =np.array([2,1,0])
def Question6(np1,np2):  
    print(np.cov(np1,np2))
Question6(np1,np2)

[[ 1. -1.]
 [-1.  1.]]


In [1]:
import math
def Question7(D):
    res=[]
    for x in D :       
        Q=(2 * 50 * x)/30
        Q=int(math.sqrt(Q))
        res.append(Q)
    return res 
lst = [ ] 
n = int(input("Enter number of elements : ")) 
D=[]
for i in range(0, n) :
    ele =int(input()) 
    D.append(ele)
Question7(D)  

Enter number of elements :  3
 100
 150
 180


[18, 22, 24]